### ISSUE TITLE
add battle pop up

### ISSUE THREAD

**Issue by scottlinder** [scottlinder/space_dungeon#16]
When a player enters a room, there needs to be a ~2 second delay. The delay is used to display a series of 2-3 sprites one after the other that relay the battle. These sprites will appear at the player location and scale up in size and then fade. The images will include the monster graphic, dice(perhaps animated), treasure graphic for victory, defeat graphic

**Comment by 5o7** [comment]
It's up. Set of 4 images, title text and describe text, dice. Image 1: close up of the beast's face. Image 2: Player attacking. Rolled dice. Text reads outcome of attack. Image 3: Monster attacking. Image 4: treasure.  If the player wins, see the treasure image. Else, see the monster attacking image. Text reads treasure won or monster's attack result.
