### ISSUE TITLE
add beast attack

### ISSUE THREAD

**Issue by scottlinder** [scottlinder/space_dungeon#2]
if not bot and player is time traveller and shock + bomb > 0
      Cast a spell?

**Comment by 5o7** [comment]
# Player kills monster
                if roll > hp:

                    print('\nOh no! %s!\nRoll the dice.' % m.name)

                    if t8 in p_hand:
                        print('+1 with Goblinblade')

                    if pa.bot: print('%sBot rolls a %d. The beast is dead.' % (pa.name, roll))
                    else: print('You roll a %d. Victory!' % roll)

                    # Make sure the monster has a treasure card
                    if len(m_hand) > 0:

                        if pa.bot: print('%sBot finds treasure:' % pa.name)
                        else: print('You find treasure:')

                        for i in range(0, len(m_hand)):
                            print(m_hand[i].name)
                            pa.gp = pa.gp + m_hand[i].amount
                            p_hand.append(m_hand[i])

                    if pa.bot: print('%sBot, has %d gp.' % (pa.name, pa.gp))
                    else: print('%s, you have %d gp.' % (pa.name, pa.gp))

**Comment by 5o7** [comment]
# Player misses. Monster attacks
                else:
                    if pa.bot: print('\n%s attack! %s roll %d and missed.' % (m.name, m.name, roll))
                    else: print('\nOh no! You missed.')
                    print('%s are rolling...' % m.name)

                    roll1 = random.randint(2, 12)
                    print('They roll a %d.' % roll)

                    # Monster misses
                    if roll <= wound_low:
                        print('They miss!')

                    # Monster lightly wounds player
                    elif wound_low < roll <= wound_mid:
                        if pa.bot: print('\n%sBot suffers a light wound.' % pa.name)
                        else: print('\n%s suffers a light wound.' % pa.name)

                        # Check if the player has any treasure cards
                        if len(p_hand) > 0:

                            # If so player drops 1 card
                            if pa.bot:
                                print('%sBot drops a %s.' % (pa.name, p_hand[0].name))
                                pa.gp = pa.gp - p_hand[0].amount
                                m_hand.append(p_hand[0])
                                p_hand.pop(0)

                            else:
                                pa, p_hand, m_hand = lose_card(pa, p_hand, m_hand)

                    # Monster seriously wounds player
                    elif wound_mid < roll <= wound_high:
                        print('The %s attack!' % m.name)
                        if pa.bot: print('\n%sBot suffers a serious wound.' % pa.name)
                        else: print('\n%s, you suffer a serious wound.' % pa.name)

                        # Check if the player has any treasure cards
                        if len(p_hand) > 0 and not p.hurt:
                            half = int(len(p_hand) / 2)

                            if half == 0:
                                half = 1

                                print('\nDrop %d cards.' % half)

                            if pa.bot:
                                for i in range(1, half):
                                    pa.gp = pa.gp - p_hand[0].amount
                                    m_hand.append(p_hand[0])
                                    p_hand.pop(0)

                            else:

                                for i in range(1, half):
                                    pa, p_hand, m_hand = lose_card(pa, p_hand, m_hand)

                        # Player suffers a critical wound
                        if expert and roll == 10 and not p.hurt:
                            p.hurt = True
                            print('Hero is critically wounded. Seek a Paladin for healing')
                            print('or get back to the Main Staircase.')

                        # Wounded player suffers another critical wound
                        if expert and roll == 10 and p.hurt:
                            print('\nHero has suffered another crtical wound and dies.')
                            print('Drop all treasure cards.\nGo to s01 and start again.')
                            pa.gp = 0
                            for i in range(0, len(p_hand)):
                                m_hand.append(p_hand[i])
                            p_hand = []
                            pa.loc = '1'

                        print('You have %d gp.' % pa.gp)

                    # Monster kills player
                    else:
                        print('Hero is slain.\nDrop all treasure cards.\nGo to s01 and start again.')
                        pa.gp = 0
                        for i in range(0, len(p_hand)):
                            m_hand.append(p_hand[i])
                        p_hand = []
                        pa.loc = '1'

**Comment by 5o7** [comment]
done
