### ISSUE TITLE
add spells

### ISSUE THREAD

**Issue by scottlinder** [scottlinder/space_dungeon#26]
Time Travellers have 3 special powers: Electroshock, Vacuum bomb, 4D portal. They get to choose 6 of these powers. They can choose 6 vacuum bombs or 2 of each.

Electroshock and Vacuum bombs are used for attacks on the beasts. The powers can be used in the beast lairs or to teleport from one space to another.

**Comment by 5o7** [comment]
Spells can be charged at start of game.
Spell inventory listed in card menu.

**Comment by 5o7** [comment]
Attack spells become available at appropriate time (next to or in a room). Attack spells can be cancelled if desired.

**Comment by 5o7** [comment]
Remove ability to cast spells while in a room. Only allow casting if next to a room.

**Comment by 5o7** [comment]
All 3 spells working. Probably some bugs but haven't found them yet. Moving on to battle scene display.
